title: "D3TIP"
description: "Site officiel du projet D3TIP (PHC Utique 2026)"
url: "https://d3tip-phc-utique.github.io"
baseurl: ""
theme: minima
minima:
  show_excerpts: false

header_pages:
  - fr/project.md
  - fr/team.md
  - fr/research.md
  - fr/events.md
  - fr/publications.md
  - fr/bibliography.md
  - fr/links.md
  - fr/partners.md
